### ISSUE TITLE
Windows: Does not supports SQL Aliases

### ISSUE THREAD

**Issue by gerardog** [dbcli/mssql-cli#100]
I have a SQL alias configured in SQL Server Configuration Manager.
The alias is named "SqlAlias" and redirects to ".\MSSQLSERVER2016" 

The following line fails to connect: mssql-cli.bat -E -S SqlAlias
On the other hand, using the natural name works fine: mssql-cli.bat -E -S .\MSSQLSERVER2016

**Comment by pensivebrian** [comment]
@gerardog - this is an interesting issue.

Currently, mssql-cli does not support the SQL Alias feature. The reason being, it's not supported by .NET Core, which is what mssql-cli uses to connect to a database (via the [SqlToolsService](https://github.com/Microsoft/sqltoolsservice)). Since SQL Alias relies on the registry, it's not a cross platform feature, so I can see why the feature was dropped in .NET Core (see issue https://github.com/dotnet/corefx/issues/2575). 

There are a couple of ways to address this, so I had some questions:

1. How import is the SQL Alias feature. Is blocking any important scenarios for you in anyway?
2. If added, are you expecting a Windows only feature that works with the registry that works with SSCM? Or a more general cross platform solution that does not work with SSCM?

It's worth mentioning, SQL Operations Studio is also impacted by this (https://github.com/Microsoft/sqlopsstudio/issues/71) since it also uses SqlToolsService.

**Comment by gerardog** [comment]
This is not a blocker for me. Seems reasonable that this should be fixed in the .net core platform as a whole.  I honestly created this as an issue assuming mssql-cli was pure python code.

**Comment by gerardog** [comment]
Regarding your 2nd question. If this feature is implemented, I would expect mssql-cli on windows to behave same as SSMS. 
A more general cross platform solution that does not work with SSCM is not of much use to me, because SQL Aliases add value only if they are a standard that many applications adhere to.
