### ISSUE TITLE
NVARCHAR DataType max length - incorrect error message

### ISSUE THREAD

**Issue by Komport** [dbcli/mssql-cli#135]
Hi All.

As you know max Length for nvarchar data type is 4000. But if you enter for Length value number greater than 8000 you will get below error. 
```
DBSIZE>CREATE TABLE test_table(some_value NVARCHAR(8001));
Msg 131, Level 15, State 2, Line 1
The size (8001) given to the column 'some_value' exceeds the maximum allowed for any data type (8000).
Time: 0.054s

```
Error message says that I can create nvarchar column with max length of 8000. Let's try. 

```
DBSIZE>CREATE TABLE test_table(some_value NVARCHAR(8000));
Msg 2717, Level 16, State 2, Line 1
The size (8000) given to the parameter 'some_value' exceeds the maximum allowed (4000).
Time: 0.054s
```

Trying to create with 4000 value. 
```
DBSIZE>CREATE TABLE test_table(some_value NVARCHAR(4000));
Commands completed successfully.
Time: 0.113s
DBSIZE>
```

**Comment by abhisheksinha89** [comment]
This message comes from the SQL Server engine itself and can be reproed using SSMS, sqlcmd, etc.
It's a bit confusing but I guess the first message tells that you have exceeded the limit for any data type which is 8000 which is probably the first check the engine does. The second message checks for the limit of NVARCHAR itself which is 4000. 

Thanks for bringing this to our notice though, but since this is not a client side issue I will close this.
Thanks.
