### ISSUE TITLE
Don't call the tool "open source"

### ISSUE THREAD

**Issue by EvanCarroll** [dbcli/mssql-cli#142]
I think it's somewhat confusing when you call the tool "open source" when it's thin python shim over a bunch of proprietary dlls.

Yea, you're on Github, but this isn't really the idea..

https://github.com/dbcli/mssql-cli/pull/127/commits/7fac173164b49abdf095da9b547a8e39099f8e51

**Comment by MrMeemus** [comment]
@EvanCarroll  thanks for the comment, the proprietary dll's you are referring to are also open sourced here: https://github.com/Microsoft/sqltoolsservice.

We welcome contributions there too! :)

**Comment by EvanCarroll** [comment]
Where is the commit that added DAC in that repository? I'm having a hard time finding it,

https://github.com/Microsoft/sqltoolsservice/commits/master

You closed this issue

https://github.com/dbcli/mssql-cli/issues/93

With this commit 

https://github.com/dbcli/mssql-cli/commit/7fac173164b49abdf095da9b547a8e39099f8e51

I don't see anything in that commit history that even mentions DAC,

https://github.com/Microsoft/sqltoolsservice/commits/master

Is Microsoft maintaining their own private of sqltoolsservice service, or are they pulling from the Git repo?

**Comment by MrMeemus** [comment]
Here is the PR that addressed the DAC fix: https://github.com/dbcli/mssql-cli/pull/127

The comments state that the fix was on the python client side along with updates from sqltoolsservice which had a updated Sqlclient. As far as the actual commit that added DAC support I am not 100% sure who or when it was commited to sqltoolsservice. I can dig that up if interested.

Microsoft maintains only a public repo of sqltoolsservice and all tools pull the latest bits from that repo.

Please let me know if you have any other questions/comments/concerns. 

Thanks!

**Comment by pensivebrian** [comment]
I tried to capture this information in my PR for #127, but perhaps I could have done a better job. 

The underlying DAC fix was made to SqlClient in PR [#10844](https://github.com/dotnet/corefx/pull/18044). SqlClient is part of the [dotnet/corefx](https://github.com/dotnet/corefx) repo. The fix was then pulled into the [sqltoolsservice](https://github.com/Microsoft/sqltoolsservice) with PR [#466](https://github.com/Microsoft/sqltoolsservice/pull/466). The sqltoolsservice is a reusable micro-service, which mssql-cli uses for all SQL Server communication. In fact, the sqltoolsservice is used by a number of SQL tools:
* [Microsoft/sqlopsstudio](https://github.com/Microsoft/sqlopsstudio)
* [Microsoft/vscode-mssql](https://github.com/Microsoft/vscode-mssql)
* [Microsoft/mssql-scripter](https://github.com/Microsoft/mssql-scripter)
* [dbcli/mssql-cli](https://github.com/dbcli/mssql-cli)

By making the fix in SqlClient and the sqltoolsservice, all other tools got the fix for free.

There are a lot of moving parts, so I wonder how could we better capture this? Perhaps an architecture diagram? I'm interested in any of your thoughts around ways to make the dependencies more clear.

Hope this helps.

**Comment by EvanCarroll** [comment]
Summary of commits
====

* [SqlClient PR #10844](https://github.com/dotnet/corefx/pull/18044) was committed on [Apr 10, 2017](https://github.com/dotnet/corefx/commit/5a7a9f0736d5a1d21bd4d6f1b7913a4c61a797cc).
* [sqltoolsservice PR #466](https://github.com/Microsoft/sqltoolsservice/pull/466) was commited on [Sept 20, 2017](https://github.com/Microsoft/sqltoolsservice/pull/466)

And this project shipped out a `sqltoolservice` for three months before it got around to updating it. That's **not** the end the world. A three month lag time isn't honestly that bad. I'm delighted all that stuff has source. Let's talk about how we can make it better.

Improvements
====

I would *not* ship out a binary zip of `sqltoolsservice`. That not a good idea. First on the matter of security, it's super sketch. We essentially have to trust Microsoft, and unless everything in that zip is a repeatable build, we *really* have to trust you. Moreover, how will security patches in `sqltoolsservice` tool work? They're going to notify any project using this distribution mechanism to rebuild against them? Doesn't this entirely invalidate the idea of shared libraries?

Upstream
----

What you need to do is,

* Provide build scripts for your Microsoft maintainers inside of `corefx` that build and push up the essential parts to PyPy that `sqltoolsservice` requires. I think the tool here is twine. https://github.com/pypa/twine
* Provide build scripts for your Microsoft maintainers inside of `sqltoolsservice` that push up the essential parts to PyPy that `mssql-cli` requires.

mssql-cli
----

Then,

* Have this package require and depend on a specific version of `sqltoolsservice` on PyPy. 
* `git filter` this distro removing *all* binary blobs, and `--force` push up a new one.

Other notes about zip
----

I'm not 100% sure as to how the zip archive works with compression, but my assumption is that this method of uploading a new zip file is extremely inefficient and any gain whatsoever made by the zip file's own compression will be totally lost by the inability for maintainers to pull down just the diff of the attached dlls. That is to say, if the zip file saves 1% in compression, it could result in an entirely new zip file increasing the size of the repository by the total size of the zip and not the delta.

**Comment by mi-hol** [comment]
@MrMeemus I wonder if the comments made by @EvanCarroll after closing will be considered?

**Comment by MrMeemus** [comment]
@EvanCarroll ,

Thank you for your thorough and thoughtful response.

> I would not ship out a binary zip of sqltoolsservice. That not a good idea. First on the matter of security, it's super sketch. We essentially have to trust Microsoft, and unless everything in that zip is a repeatable build, we really have to trust you. Moreover, how will security patches in sqltoolsservice tool work? They're going to notify any project using this distribution mechanism to rebuild against them? Doesn't this entirely invalidate the idea of shared libraries?

**Response:** mssql-cli does not ship zipped binaries of sqltoolsservice, but rather the official binaries of the latest github release of sqltoolsservice per supported distro/OS. If you disagree with the distribution format of sqltoolsservice, I would recommend filing a issue there as I don't know the entire details of their distribution route. 

One thing that I really liked from your suggestion was the idea of how to track which sqltoolsservice was released with mssql-cli, we can update our release notes and provide some mechanism for versioning to verify the release match up.

> Provide build scripts for your Microsoft maintainers inside of sqltoolsservice that push up the essential parts to PyPy that mssql-cli requires.

**Response:** Originally when we release mssql-scripter we had a individual sqltoolsservice package hosted on PYPI. This was redesigned after because:
1. **Maintenance and dependency**
    With more than 1 python tool relying on sqltoolsservice, we decided it would be best for each tool to be self contained and ship it's own necessary version of sqltoolsservice. This prevents any cross version dependency where if a user has both mssql-cli and mssq-scripter installed, and sqltoolsservice introduces a breaking change, we wouldn't want to break both tools. Rather we want each tool to operate independently with only the latest necessary sqltoolsservice.

   Your suggestion of shipping only the necessary parts of sqltoolsservice on PYPI may even lead to more confusion because if another tool needs a different part of the library, the sqltoolsservice python package would have to be renamed because PYPI only supports unique package names. Multiplying this by 7 - 12 packages of sqltoolsservice per OS/Distro leads to a maintainers nightmare. 

2. **Wheels Wheels Wheels**
    If we went the route of hosting sqltoolsservice on PYPI (after we get through the troubles mentioned above), we would have 7 - 12 sqltoolsservice python packages each containing their own dll's and OS specific libraries. In order to ship mssql-cli or mssql-scripter both tools would require platform detection during install time to pull down the right version and name of sqltoolsservice for host OS. Being self contained allows us to upload wheels rather then our source code to PYPI and decreases install time.

After looking through your notes and thoughts, it seems like your main concern is being able to track what changes went into where and when. Simply stating "Refreshing binaries from sqltoolsservice" may not suffice and we can work to make this process more transparent. 


Thanks,
Ron

**Comment by EvanCarroll** [comment]
> we decided it would be best for each tool to be self contained and ship it's own necessary version of sqltoolsservice. This prevents any cross version dependency where if a user has both mssql-cli and mssq-scripter installed, and sqltoolsservice introduces a breaking change, we wouldn't want to break both tools. Rather we want each tool to operate independently with only the latest necessary sqltoolsservice.

I'm not the person to tell you about alternative methods. But I'm fairly certain (99% and some change), that you're going about this wrong and that you'll regret it at some time in the future. I even asked a quick question on [StackOverflow for some clarification,](https://stackoverflow.com/a/48346227/124486)

> To develop with FOO V1 and FOO V2 concurrently on the same computer you would have to use virtualenv and create a separate virtual environment where each version of FOO will reside without interfering. Each will have it's own site-packages carrying each one specific version of the package.

So the python way is to create a different "virtualenv" for each package. It's simply not true that in the  alternative *"each tool [must] operate independently with only the latest necessary sqltoolsservice."* You can upload multiple versions to PyPI and have each tool in their own `virtualenv` tracking what version to use. The advantage being you're not having to maintain each tool for the dependency. You can just operate off of semvar -- a change upstream in `sqltoolsservice` will propagate down when and only when you want.

**Comment by amjith** [comment]
@EvanCarroll The virtualenv is a concept that is used for development. It is typically used by Python devs who are familiar with it. 

Asking everyone who wants to use mssql-cli to learn how to use a virtualenv is not a user friendly approach. 

It is common (in python world) to vendor in the dependencies to avoid conflicts.
