### ISSUE TITLE
Install mycli and mssql-cli conflicts at the same time

### ISSUE THREAD

**Issue by 0clickjacking0** [dbcli/mssql-cli#239]
I have a problem.My os is Windows10.In my computer have python2.7 and python3.7,the python2.7 is in C:\,and the python3.7 is in E:\,they are not in conflict.My command to download mycli is 'pip3 install mycli',and my command to download mssql-cli is 'pip3 install mssql-cli',If I only install mycli, then mycli can use,but if i install mycli and mssql-cli,they can't work.Please help me, I have been searching for google for a long time, still no problem to solve, thank you！！

![q_mycli_mssqlcli](https://user-images.githubusercontent.com/40328559/52187306-af577e00-2867-11e9-9b90-3cc4166127aa.png)

**Comment by MrMeemus** [comment]
Hi @0clickjacking0 , This issue is due to the dependency on prompt tool kit which mssql-cli has not been updated to version 2.0 , which is the version now installed by mycli. I have a branch out with this update and will send out a PR shortly after more testing. Sorry for the inconvenience, it should be fixed within the next week!

**Comment by 0clickjacking0** [comment]
OK ，Thanks! @MrMeemus

**Comment by pensivebrian** [comment]
The mssql-cli 0.16.0 release supports prompt_toolkit 2.0, so mycli and mssql-cli should now be compatible.
