### ISSUE TITLE
app fails to execute merge statement and reports "A MERGE statement must be terminated by a semi-colon (;)."

### ISSUE THREAD

**Issue by aberezin-acertus** [dbcli/mssql-cli#422]
Version: 0.18.0
Under bash, using the attached sql file, exec 
`mssql-cli -U $user -d $database -S $host -i test-basic-merge.sql`

Get error "A MERGE statement must be terminated by a semi-colon (;)."

This file properly executes using another client, DataGrip.

[test-basic-merge.sql.txt](https://github.com/dbcli/mssql-cli/files/4248168/test-basic-merge.sql.txt)

**Comment by ellbosch** [comment]
Thanks for posting this—looks like a valid bug to me. I tested this query with Azure Data Studio and it seems to work fine there. I'll take a look at this.

**Comment by aberezin-acertus** [comment]
Thanks.  It will be a problem for lots of sql command interpreters.  I just logged the same bug with sqlline.  Almost every sql command app uses semicolon for its own parser and then strips it :(

**Comment by ellbosch** [comment]
@aberezin-acertus I've just proposed a PR to fix this bug. This PR also will add the script you shared to our tests, so hopefully we won't hit this again.

Thanks again for posting this bug! We'll keep you posted when the PR is merged so that you may use an insider version of mssql-cli to unblock you. Expect a stable release to come out sometime March.
